In [35]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [36]:
import pandas as pd
import numpy as np

In [40]:
data = {
 'trip_id': ['T001','T002','T003','T004','T005','T006','T007','T008','T009','T010'],
 'mode': ['Taxi','Bus','Bike','Taxi','Bus','Taxi','Bike','Bus','Taxi','Taxi'],
 'distance_km': [8.4,6.1,3.2,2.7,14.3,5.1,4.0,9.8,32.0,-1.5],
 'fare_cad': [19.5,3.75,0,11.2,3.75,13.2,0,3.75,72.0,15.0],
 'wait_min': [6,9,4,12,18,np.nan,3,11,55,8],
 'rating': [4,3,5,2,2,4,5,np.nan,1,3],
 'peak': ['No','Yes','No','Yes','Yes','No','No','Yes','Yes','Yes']
}

df = pd.DataFrame(data)

In [47]:
# one-hot encoding for nominal categories
df_encoded = pd.get_dummies(df, columns=['mode'], dtype=int)

df_encoded

,trip_id,distance_km,fare_cad,wait_min,rating,peak,mode_oe,mode_Bike,mode_Bus,mode_Taxi
0,T001,8.4,19.50,6.0,4.0,No,0.0,0,0,1
1,T002,6.1,3.75,9.0,3.0,Yes,1.0,0,1,0
2,T003,3.2,0.00,4.0,5.0,No,2.0,1,0,0
3,T004,2.7,11.20,12.0,2.0,Yes,0.0,0,0,1
4,T005,14.3,3.75,18.0,2.0,Yes,1.0,0,1,0
5,T006,5.1,13.20,NaN,4.0,No,0.0,0,0,1
6,T007,4.0,0.00,3.0,5.0,No,2.0,1,0,0
7,T008,9.8,3.75,11.0,NaN,Yes,1.0,0,1,0
8,T009,32.0,72.00,55.0,1.0,Yes,0.0,0,0,1
9,T010,-1.5,15.00,8.0,3.0,Yes,0.0,0,0,1

In [46]:
type(mode_onehot)

pandas.core.frame.DataFrame

In [44]:
from sklearn.preprocessing import OrdinalEncoder

enc = OrdinalEncoder(
    categories=[['Taxi','Bus','Bike']]
)
df['mode_oe'] = enc.fit_transform(
    df[['mode']]
)

In [45]:
df

  trip_id  mode  distance_km  fare_cad  wait_min  rating peak  mode_oe
0    T001  Taxi          8.4     19.50       6.0     4.0   No      0.0
1    T002   Bus          6.1      3.75       9.0     3.0  Yes      1.0
2    T003  Bike          3.2      0.00       4.0     5.0   No      2.0
3    T004  Taxi          2.7     11.20      12.0     2.0  Yes      0.0
4    T005   Bus         14.3      3.75      18.0     2.0  Yes      1.0
5    T006  Taxi          5.1     13.20       NaN     4.0   No      0.0
6    T007  Bike          4.0      0.00       3.0     5.0   No      2.0
7    T008   Bus          9.8      3.75      11.0     NaN  Yes      1.0
8    T009  Taxi         32.0     72.00      55.0     1.0  Yes      0.0
9    T010  Taxi         -1.5     15.00       8.0     3.0  Yes      0.0